import "../../styles/globals.scss";
import "../../styles/reset.css";
import Providers from "../app/Providers";
import ThemeSwitcher from "./ThemeSwitcher";

export const metadata = {
  title: "My FastKart",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Providers>
          {children}
        </Providers>
      </body>
    </html>
  );
}
